version: '3'

services:
  # Streamlit web application
  streamlit:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      - MPLCONFIGDIR=/tmp/matplotlib
      - PYTHONVERBOSE=1
    restart: unless-stopped
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]

  # FastAPI API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]